---



- name: FIFA Configuration for two vms
  hosts: remote_servers
  become: yes
  tasks:

    #obj3.1
    - name: Install packages
      apt:
        name:
          - ftp
          - apache2
          - python3-pip
          - expect
        state: present
      loop:
        - ftp
        - apache2
        - python3-pip
        - expect

    #Obj3.2
    - name: Create groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - Attack
        - Defense
        - Captain

    - name: Create users and assign to groups
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        append: yes
      loop:
        - { name: 'hkewell', groups: 'Attack' }
        - { name: 'mowen', groups: 'Defense' }
        - { name: 'jcarra', groups: 'Defense' }
        - { name: 'dagger', groups: 'Defense' }
        - { name: 'sgerrard', groups: 'Captain,Defense' }
        - { name: 'lfigo', groups: 'Attack' }
        - { name: 'rsoldado', groups: 'Defense' }
        - { name: 'rcarlos', groups: 'Defense' }
        - { name: 'fcannavaro', groups: 'Defense' }
        - { name: 'zzidane', groups: 'Captain,Defense' }

    - name: Set permissions
      file:
        path: "/home/{{ item.name }}"
        owner: "{{ item.name }}"
        group: "{{ item.group }}" 
        mode: "{{ item.perm }}"
      loop:
        - { name: 'hkewell', group: 'Attack', perm: '0666' }
        - { name: 'mowen', group: 'Defense', perm: '0111' }
        - { name: 'jcarra', group: 'Defense', perm: '0111' }
        - { name: 'dagger', group: 'Defense', perm: '0111' }
        - { name: 'sgerrard', group: 'Captain', perm: '0777' }
        - { name: 'lfigo', group: 'Attack', perm: '0666' }
        - { name: 'rsoldado', group: 'Defense', perm: '0111' }
        - { name: 'rcarlos', group: 'Defense', perm: '0111' }
        - { name: 'fcannavaro', group: 'Defense', perm: '0111' }
        - { name: 'zzidane', group: 'Captain', perm: '0777' }


    ##Obj3.3
    - name: Create Route_Info directory
      file:
        path: "/{{ inventory_hostname }}_Admin/Route_Info/"
        state: directory
        owner: "sgerrard" 
        group: "Captain"
        mode: "0770"

    - name: create Captain_Details.txt
      copy:
        dest: "/{{ inventory_hostname }}_Admin/Route_Info/Captain_Details.txt"
        content: |
          Full Name: Steven Gerrard (for Liverpool)
          Nationality: England
          Username: sgerrard
        owner: "sgerrard"
        group: "Captain"
        mode: "0644"

    #Obj3.4
    - name: Install net-tools
      apt:
        name: net-tools
        state: present
      become: yes

    - name: Route table
      shell: netstat -r > /tmp/{{ inventory_hostname }}_route_table.txt

    - name: top10 memory-consuming processes
      shell: ps aux --sort=-%mem | head -11 > /tmp/{{ inventory_hostname }}_top_processes.txt

    - name: transfer files to netman main vm 
      expect:
        command: scp /tmp/{{ inventory_hostname }}_route_table.txt /tmp/{{ inventory_hostname }}_top_processes.txt netman@10.224.76.222:/home/netman/lab6-ansible
        responses:
          "password:": "netman"


    #3.5 ssh part
    - name: Collect and assemble ssh public keys into a single file
      shell: "cat /home/{{ item }}/.ssh/id_rsa.pub >> /root/.ssh/{{ inventory_hostname }}_authorizedKeys.txt"
      become: yes
      loop:
        - mowen
        - dagger
        - sgerrard
        - lfigo
        - fcannavaro
        - zzidane
    #- name: Ensure only public keys are in authorizedKeys files
    #  shell: "grep '^ssh-rsa' /root/.ssh/{{ inventory_hostname }}_authorizedKeys.txt > /root/.ssh/tmp_keys && mv /root/.ssh/tmp_keys /root/.ssh/{{ inventory_hostname }}_authorizedKeys.txt"
    #  become: yes
    - name: Copy keys to main VM
      expect:
        command: scp "/root/.ssh/{{ inventory_hostname }}_authorizedKeys.txt" netman@10.224.76.222:/home/netman/lab6-ansible/
        responses:
          "password:": "netman"

    - name: Import playBooks extra
      debug:
        msg: "import 2 extra yaml files"
        
...