---
- name: Configure IBGP on Cisco Routers
  hosts: routers
  gather_facts: no
  tasks:

    - name: Configure IBGP - Router ID and AS
      ios_config:
        lines:
          - "router bgp 100"
          - "bgp router-id {{ ansible_host }}"
      when: ansible_network_os == "ios"

    - name: Configure IBGP Neighbors
      ios_config:
        lines:
          - "router bgp 100"
          - "neighbor 198.51.100.3 remote-as 100"
          - "neighbor 20.20.20.1 remote-as 100"
          - "neighbor 22.22.22.1 remote-as 100"
          - "neighbor 198.51.100.3 update-source Loopback0"
          - "neighbor 20.20.20.1 update-source Loopback0"
          - "neighbor 22.22.22.1 update-source Loopback0"
      when: ansible_network_os == "ios"

    - name: Configure IBGP Neighbors on R2
      ios_config:
        lines:
          - "router bgp 100"
          - "neighbor 198.51.100.1 remote-as 100"
          - "neighbor 10.10.10.1 remote-as 100"
          - "neighbor 11.11.11.1 remote-as 100"
          - "neighbor 198.51.100.1 update-source Loopback0"
          - "neighbor 10.10.10.1 update-source Loopback0"
          - "neighbor 11.11.11.1 update-source Loopback0"
      when: ansible_host == "198.51.100.3"

    - name: Advertise Networks
      ios_config:
        lines:
          - "router bgp 100"
          - "network 10.0.0.0 mask 255.255.255.0"
          - "network 192.168.1.0 mask 255.255.255.0"
      when: ansible_network_os == "ios"

    - name: Save Running Config
      ios_command:
        commands:
          - "write memory"

    - name: Verify BGP Peering
      ios_command:
        commands:
          - "show ip bgp summary"
      register: bgp_output

    - name: Display IBGP Peering Status
      debug:
        msg: "{{ bgp_output.stdout_lines }}"
